client_config_backend: settings
client_config:
  client_id:  459659743702-31l7ggk8jfcghov91p3m18m2b5euctjj.apps.googleusercontent.com 
  client_secret: _eStLrACHg0xRjf8Y8LK04Nr 

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
